/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TodoTodoidImport } from './routes/todo/$todoid'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TodoTodoidRoute = TodoTodoidImport.update({
  id: '/todo/$todoid',
  path: '/todo/$todoid',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/todo/$todoid': {
      id: '/todo/$todoid'
      path: '/todo/$todoid'
      fullPath: '/todo/$todoid'
      preLoaderRoute: typeof TodoTodoidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/todo/$todoid': typeof TodoTodoidRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/todo/$todoid': typeof TodoTodoidRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/todo/$todoid': typeof TodoTodoidRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/todo/$todoid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/todo/$todoid'
  id: '__root__' | '/' | '/todo/$todoid'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TodoTodoidRoute: typeof TodoTodoidRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TodoTodoidRoute: TodoTodoidRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/todo/$todoid"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/todo/$todoid": {
      "filePath": "todo/$todoid.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
